remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme

title: "Variability in Behavioral Research"
description: ""

sidebar_links
  - title: Home
    url: /
  - title: Articles
    url: /docs/

collections:
  docs:
    output: true
