remote_theme: remote_theme: poole/lanyon
plugins:
- jekyll-remote-theme

title: "Variability in Behavioral Research"
description: ""

header_pages
  - title: Home
    url: /
  - title: Articles
    url: /docs/

collections:
  docs:
    output: true
