remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
title: "Variability"
description: "A tutorial on variability in theory and data analysis"
collections:
  docs:
    output: true
